#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

###################################################################
######Above is generated automatically, below is added by sunhh.###

# ---------- Prompt ----------
#PS1='\[\e[0;31m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[0;31m\]\$ \[\e[m\]\[\e[0;32m\] '
PS1='\[\e[0;42m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[0;32m\]\$ \[\e[m\]\[\e[0;32m\]'

# ---------- 补全 ----------
complete -cf sudo
complete -cf man

# ---------- 共享 aliases ----------
# 获取当前脚本所在目录
if [[ -n "$BASH_SOURCE" ]]; then
    _rc_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    [[ -f "$_rc_dir/shrc_common" ]] && source "$_rc_dir/shrc_common"
fi
