" -*- vimrc -*-
" 基本设置
filetype plugin indent on
syntax on
set encoding=utf-8
set number
set cursorline
set showcmd
set showmode
set hlsearch
set mouse=a
set helplang=cn
set fileencodings=utf8,cp936,gb18030,big5

" 括号自动补全
inoremap ' ''<ESC>i
inoremap " ""<ESC>i
inoremap ( ()<ESC>i
inoremap ) ()<ESC>a
inoremap [ []<ESC>i
inoremap ] []<ESC>a
inoremap { {}<ESC>i
inoremap } {}<ESC>a

" 窗口切换
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" F5 编译运行
nnoremap <F5> :call CompileRun()<CR>
func! CompileRun()
    exec "w"
    if &filetype == 'c'
        exec "!gcc % -o %< && time ./%<"
    elseif &filetype == 'cpp'
        exec "!g++ % -o %< && time ./%<"
    elseif &filetype == 'sh'
        exec "!time bash -x %"
    elseif &filetype == 'python'
        exec "!time python3 %"
    elseif &filetype == 'julia'
        exec "!time julia %"
    endif
endfunc

" 语言缩进设置
au BufNewFile,BufRead *.py,*.jl set tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent
au BufNewFile,BufRead *.tex set tabstop=4 softtabstop=4 shiftwidth=4 expandtab

" 主题
colorscheme desert
